import Foundation

public enum AppLanguagePreference: String, CaseIterable, Identifiable {
    case english
    case german

    public var id: String { rawValue }
    public var isGerman: Bool { self == .german }

    public var title: String {
        switch self {
        case .english:
            return "English"
        case .german:
            return "Deutsch"
        }
    }

    public var locale: Locale {
        switch self {
        case .english:
            return Locale(identifier: "en")
        case .german:
            return Locale(identifier: "de")
        }
    }

    public func localized(_ english: String) -> String {
        switch self {
        case .english:
            return english
        case .german:
            return AppGermanTranslations.values[english] ?? english
        }
    }

    public func localized(format englishFormat: String, arguments: [CVarArg]) -> String {
        let format = localized(englishFormat)
        return String(format: format, locale: locale, arguments: arguments)
    }
}

enum AppGermanTranslations {
    static let values: [String: String] = [
        "Overview": "Übersicht",
        "Days": "Tage",
        "Insights": "Einblicke",
        "Export": "Export",
        "Options": "Optionen",
        "Actions": "Aktionen",
        "Clear": "Leeren",
        "Done": "Fertig",
        "Saved Live Tracks": "Gespeicherte Live-Tracks",
        "Open Library": "Mediathek öffnen",
        "No Results": "Keine Treffer",
        "All": "Alle",
        "Primary Actions": "Wichtige Aktionen",
        "Browse Days": "Tage ansehen",
        "Get Started": "Loslegen",
        "Import a location history file to explore your journeys, export tracks and see insights.": "Importiere eine Standortverlaufs-Datei, um Reisen zu erkunden, Tracks zu exportieren und Einblicke zu erhalten.",
        "Processed locally · JSON, ZIP, GPX, TCX": "Lokal verarbeitet · JSON, ZIP, GPX, TCX",
        "Data processed locally. Supported formats: JSON, ZIP, GPX, TCX": "Lokal verarbeitet. Unterstützte Formate: JSON, ZIP, GPX, TCX",
        "Open Insights": "Einblicke öffnen",
        "Export GPX": "GPX exportieren",
        "Highlights": "Highlights",
        "Busiest Day": "Aktivster Tag",
        "Longest Distance": "Längste Strecke",
        "Total Distance": "Gesamtstrecke",
        "Filtered Export": "Gefilterter Export",
        "No Insights Available": "Keine Einblicke verfügbar",
        "Load a location history file to see detailed insights.": "Lade eine Standortverlauf-Datei, um detaillierte Einblicke zu sehen.",
        "Select a day from the list to view details.": "Wähle einen Tag aus der Liste, um Details zu sehen.",
        "Back to Overview": "Zurück zur Übersicht",
        "Local Recording": "Lokale Aufzeichnung",
        "Current position and saved live tracks stay separate from imported history.": "Aktuelle Position und gespeicherte Live-Tracks bleiben von importierter Historie getrennt.",
        "Record": "Aufzeichnen",
        "Record live track": "Live-Track aufzeichnen",
        "Current Location": "Aktueller Standort",
        "Center on current location": "Auf aktuellen Standort zentrieren",
        "Live location is off": "Live-Standort ist aus",
        "Turn recording on to request foreground-only location access and draw a live track.": "Aktiviere die Aufzeichnung, um Standortzugriff im Vordergrund anzufordern und einen Live-Track zu zeichnen.",
        "Distance Units": "Entfernungseinheiten",
        "Start Tab": "Start-Tab",
        "Show Technical Import Details": "Technische Importdetails anzeigen",
        "Display": "Anzeige",
        "Controls how much metadata the app shows around imports and source information.": "Steuert, wie viele Metadaten die App rund um Importe und Quelleninformationen anzeigt.",
        "Default Map Style": "Standard-Kartenstil",
        "Maps": "Karten",
        "Applies to the day-detail map and live-location map.": "Gilt für die Tagesdetail-Karte und die Live-Standort-Karte.",
        "Accuracy Filter": "Genauigkeitsfilter",
        "Recording Detail": "Aufzeichnungsdetail",
        "Allow Background Recording": "Hintergrundaufzeichnung erlauben",
        "Accepted Accuracy": "Akzeptierte Genauigkeit",
        "Minimum Movement": "Mindestbewegung",
        "Minimum Time Gap": "Minimaler Zeitabstand",
        "Maximum Time Gap": "Maximaler Zeitabstand",
        "No minimum": "Kein Minimum",
        "Unlimited": "Unbegrenzt",
        "Background recording requires Always Allow permission and only affects local live-track recording.": "Hintergrundaufzeichnung erfordert die Berechtigung 'Immer erlauben' und betrifft nur die lokale Live-Track-Aufzeichnung.",
        "Server Upload": "Server-Upload",
        "Language": "Sprache",
        "Upload to Your Own Server": "Auf eigenen Server hochladen",
        "Server URL": "Server-URL",
        "Bearer Token (optional)": "Bearer-Token (optional)",
        "Language and Upload": "Sprache und Upload",
        "Choose the app language and optionally forward accepted live-recording points to your own endpoint. Upload stays off until a valid URL is present.": "Wähle die App-Sprache und leite akzeptierte Live-Aufzeichnungspunkte optional an deinen eigenen Endpunkt weiter. Der Upload bleibt aus, bis eine gültige URL vorhanden ist.",
        "Privacy": "Datenschutz",
        "Location Data": "Standortdaten",
        "Stored locally on this device": "Lokal auf diesem Gerät gespeichert",
        "Foreground + optional background": "Vordergrund + optional Hintergrund",
        "Foreground only": "Nur Vordergrund",
        "This app keeps imports and live tracks local by default. Server upload is optional, user-controlled and only sends accepted live-recording points to the configured endpoint.": "Diese App hält Importe und Live-Tracks standardmäßig lokal. Server-Upload ist optional, nutzergesteuert und sendet nur akzeptierte Live-Aufzeichnungspunkte an den konfigurierten Endpunkt.",
        "Technical": "Technisch",
        "Reset Options": "Optionen zurücksetzen",
        "Kilometers": "Kilometer",
        "Miles": "Meilen",
        "Standard": "Standard",
        "Satellite Hybrid": "Satellit Hybrid",
        "Relaxed": "Locker",
        "Balanced": "Ausgewogen",
        "Strict": "Strikt",
        "Battery Saver": "Batteriesparer",
        "Detailed": "Detailliert",
        "Recording Interval": "Aufnahmeintervall",
        "Interval Unit": "Intervall-Einheit",
        "Every": "Alle",
        "Seconds": "Sekunden",
        "Second": "Sekunde",
        "seconds": "Sekunden",
        "second": "Sekunde",
        "Minutes": "Minuten",
        "Minute": "Minute",
        "minutes": "Minuten",
        "minute": "Minute",
        "Hours": "Stunden",
        "Hour": "Stunde",
        "hours": "Stunden",
        "hour": "Stunde",
        "Recording Interval sets a hard floor on how often a point is accepted – larger values reduce point count, battery use and upload frequency.": "Das Aufnahmeintervall legt fest, wie oft mindestens ein Punkt akzeptiert wird – größere Werte reduzieren die Punktanzahl, den Akkuverbrauch und die Upload-Häufigkeit.",
        "Minimum Time Gap controls the shortest allowed delay between accepted points. Set it to No minimum to disable the hard floor.": "Der minimale Zeitabstand legt die kürzeste erlaubte Verzögerung zwischen akzeptierten Punkten fest. Setze ihn auf Kein Minimum, um die harte Untergrenze zu deaktivieren.",
        "Larger minimum gaps reduce point count, battery use and upload frequency.": "Größere minimale Zeitabstände reduzieren die Punktanzahl, den Akkuverbrauch und die Upload-Häufigkeit.",
        "Maximum Time Gap is unlimited.": "Der maximale Zeitabstand ist unbegrenzt.",
        "Recording Detail still tunes the movement-sensitive quality gate.": "Die Aufzeichnungsdetail-Stufe justiert weiterhin den bewegungssensitiven Qualitätsfilter.",
        "Waiting for Location Permission": "Warte auf Standortfreigabe",
        "Location Permission Not Requested": "Standortfreigabe nicht angefordert",
        "Location Access Restricted": "Standortzugriff eingeschränkt",
        "Location Access Denied": "Standortzugriff verweigert",
        "Background Access Required": "Hintergrundfreigabe erforderlich",
        "Recording in Background": "Aufzeichnung im Hintergrund",
        "Background Upgrade Pending": "Hintergrundfreigabe ausstehend",
        "Recording Live Track": "Live-Track wird aufgezeichnet",
        "Live Location Ready": "Live-Standort bereit",
        "Search by date": "Nach Datum suchen",
        "Search by date, weekday or month": "Nach Datum, Wochentag oder Monat suchen",
        "This app currently has no cloud sync and no server transfer. Background recording remains local to this device and still depends on Apple location permission.": "Diese App hat derzeit keine Cloud-Synchronisierung und keinen Servertransfer. Hintergrundaufzeichnung bleibt lokal auf diesem Gerät und hängt weiterhin von Apples Standortfreigabe ab.",
        "English": "Englisch",
        "Accepts up to 100 m accuracy.": "Akzeptiert bis zu 100 m Genauigkeit.",
        "Accepts up to 65 m accuracy.": "Akzeptiert bis zu 65 m Genauigkeit.",
        "Accepts up to 25 m accuracy.": "Akzeptiert bis zu 25 m Genauigkeit.",
        "Fewer stored points, larger movement threshold.": "Weniger gespeicherte Punkte, höherer Bewegungs-Schwellwert.",
        "Default spacing for local live tracks.": "Standardabstand für lokale Live-Tracks.",
        "Keeps more movement detail with tighter thresholds.": "Behält mehr Bewegungsdetails mit engeren Schwellwerten.",
        "App Language": "App-Sprache",
        "Open the Export tab to review or save the current selection.": "Öffne den Export-Tab, um die aktuelle Auswahl zu prüfen oder zu sichern.",
        "Accepted live-recording points only. Use an HTTP(S) endpoint you control.": "Nur akzeptierte Live-Aufzeichnungspunkte. Nutze einen HTTP(S)-Endpunkt unter deiner Kontrolle.",
        "Active": "Aktiv",
        "Enabled": "Aktiv",
        "Disabled": "Deaktiviert",
        "Enabled (invalid URL)": "Aktiv (ungültige URL)",
        "Dynamic Island Value": "Dynamic-Island-Wert",
        "Failed": "Fehlgeschlagen",
        "Live Activities": "Live-Aktivitäten",
        "Upload status": "Upload-Status",
        "Upload Status": "Upload-Status",
        "Import your location history": "Importiere deinen Standortverlauf",
        "Private location history → GPX, KML, CSV, KMZ": "Privater Standortverlauf → GPX, KML, CSV, KMZ",
        "Open an app_export.json or .zip from the LocationHistory2GPX tool — or a Google Timeline location-history.json or .zip from Google Takeout.": "Öffne eine app_export.json oder .zip aus dem LocationHistory2GPX-Tool oder eine Google-Timeline-location-history.json bzw. .zip aus Google Takeout.",
        "Open an LH2GPX app_export.json or .zip from the LocationHistory2GPX tool — or a Google Timeline location-history.json or .zip from Google Takeout.": "Öffne eine LH2GPX-app_export.json oder .zip aus dem LocationHistory2GPX-Tool oder eine Google-Timeline-location-history.json bzw. .zip aus Google Takeout.",
        "Import File": "Datei importieren",
        "Open location history file": "Standortverlauf-Datei öffnen",
        "Open Days": "Tage öffnen",
        "Load Demo Data": "Demodaten laden",
        "Open Another File": "Andere Datei öffnen",
        "Demo Data": "Demodaten",
        "Reload Demo": "Demo neu laden",
        "Opening location history...": "Standortverlauf wird geöffnet...",
        "Loading demo app export...": "Demo-App-Export wird geladen...",
        "Load Demo": "Demo laden",
        "Import JSON": "JSON importieren",
        "No demo source loaded": "Keine Demoquelle geladen",
        "Load the bundled demo fixture or import a local app_export.json file.": "Lade die gebündelte Demo-Datei oder importiere eine lokale app_export.json-Datei.",
        "Nothing to Export": "Nichts zu exportieren",
        "Import a location history file or save a live track first to enable export.": "Importiere zuerst eine Standortverlauf-Datei oder speichere einen Live-Track, um den Export zu aktivieren.",
        "Select All": "Alle auswählen",
        "Deselect All": "Auswahl aufheben",
        "Preview": "Vorschau",
        "Review Selection": "Auswahl prüfen",
        "Review in Days": "In Tage prüfen",
        "Review your selection, confirm the file format and then export a real generated file.": "Prüfe deine Auswahl, bestätige das Dateiformat und exportiere dann eine echte generierte Datei.",
        "Choose the days or saved live tracks you want to review before exporting.": "Wähle die Tage oder gespeicherten Live-Tracks aus, die du vor dem Export prüfen möchtest.",
        "No exportable days or tracks are selected yet.": "Es sind noch keine exportierbaren Tage oder Tracks ausgewählt.",
        "Start from Days to pick one or more dates, or import a file first if your history is still empty.": "Gehe zu Tage, um ein oder mehrere Daten auszuwählen, oder importiere zuerst eine Datei, wenn deine Historie noch leer ist.",
        "Select at least one day or saved live track to unlock the preview.": "Wähle mindestens einen Tag oder einen gespeicherten Live-Track aus, um die Vorschau zu aktivieren.",
        "No stable map preview is available for the current selection.": "Für die aktuelle Auswahl ist keine stabile Kartenvorschau verfügbar.",
        "Choose Format": "Format wählen",
        "What to include": "Was enthalten sein soll",
        "Save or Share": "Sichern oder Teilen",
        "Export Destination": "Exportziel",
        "Saved live tracks are exported through the same system sheet and remain local unless you explicitly share the generated file.": "Gespeicherte Live-Tracks werden über dieselbe Systemfreigabe exportiert und bleiben lokal, solange du die generierte Datei nicht ausdrücklich teilst.",
        "Filter Imported History": "Importierte Historie filtern",
        "Mode": "Modus",
        "Format": "Format",
        "No recorded entries": "Keine erfassten Einträge",
        "No recorded entries for this day": "Keine erfassten Einträge für diesen Tag",
        "No days match \"%@\".": "Keine Tage passen zu \"%@\".",
        "Export markers stay visible directly in the list.": "Export-Markierungen bleiben direkt in der Liste sichtbar.",
        "No Days": "Keine Tage",
        "This export does not contain any day entries.": "Dieser Export enthält keine Tageinträge.",
        "Nothing Recorded": "Nichts aufgezeichnet",
        "This day has no visits, activities or paths in the export.": "Dieser Tag enthält im Export keine Besuche, Aktivitäten oder Routen.",
        "Select a Day": "Tag auswählen",
        "Choose a day from the list to view details.": "Wähle einen Tag aus der Liste, um Details anzuzeigen.",
        "No Day Entries": "Keine Tageinträge",
        "Import a file with day entries to view details.": "Importiere eine Datei mit Tageinträgen, um Details anzuzeigen.",
        "Imported Day Data": "Importierte Tagesdaten",
        "Map, timeline and entry cards below come from the currently imported history file.": "Karte, Zeitachse und Eintragskarten unten stammen aus der aktuell importierten Historie.",
        "Map view requires iOS 17 or later.": "Die Kartenansicht benötigt iOS 17 oder neuer.",
        "Timeline": "Zeitachse",
        "Activities": "Aktivitäten",
        "Route": "Route",
        "Imported History": "Importierte Historie",
        "Saved tracks are local recordings. They stay separate from imported history until you open one for editing.": "Gespeicherte Tracks sind lokale Aufzeichnungen. Sie bleiben von der importierten Historie getrennt, bis du einen zum Bearbeiten öffnest.",
        "No saved live tracks yet.": "Noch keine gespeicherten Live-Tracks.",
        "Go to any day, open Local Recording, record a short track and switch Record off. The finished track will appear here.": "Gehe zu einem beliebigen Tag, öffne Lokale Aufzeichnung, nimm einen kurzen Track auf und schalte Aufzeichnen wieder aus. Der fertige Track erscheint dann hier.",
        "Summary": "Zusammenfassung",
        "Date": "Datum",
        "Started": "Gestartet",
        "Ended": "Beendet",
        "Points": "Punkte",
        "Map Preview": "Kartenvorschau",
        "Start": "Start",
        "End": "Ende",
        "Point %d": "Punkt %d",
        "Latitude": "Breitengrad",
        "Longitude": "Längengrad",
        "Accuracy (m)": "Genauigkeit (m)",
        "Insert Midpoint": "Mittelpunkt einfügen",
        "Reset": "Zurücksetzen",
        "Save": "Speichern",
        "Delete": "Löschen",
        "Delete saved track?": "Gespeicherten Track löschen?",
        "Delete Track": "Track löschen",
        "This removes the saved track from local storage.": "Dadurch wird der gespeicherte Track aus dem lokalen Speicher entfernt.",
        "Loading...": "Wird geladen...",
        "Source": "Quelle",
        "Schema": "Schema",
        "Exported": "Exportiert",
        "Technical Details": "Technische Details",
        "Distance Over Time": "Strecke im Zeitverlauf",
        "Tap a bar to open the corresponding day.": "Tippe auf einen Balken, um den zugehörigen Tag zu öffnen.",
        "Route distances only": "Nur Routendistanzen",
        "Route distance with recorded-trace fallback.": "Routendistanz mit Fallback auf aufgezeichnete Spur-Geometrie.",
        "Route distance with recorded-trace fallback. Tap a bar to open that day.": "Routendistanz mit Fallback auf aufgezeichnete Spur-Geometrie. Tippe auf einen Balken, um diesen Tag zu öffnen.",
        "No Route Distances": "Keine Routendistanzen",
        "This import does not contain route distance data that could be plotted over time.": "Dieser Import enthält keine Routendistanzdaten, die über die Zeit dargestellt werden könnten.",
        "No route distance or recorded trace data is available for these days.": "Für diese Tage sind weder Routendistanzen noch aufgezeichnete Spur-Daten verfügbar.",
        "Charts Unavailable": "Diagramme nicht verfügbar",
        "This platform build does not include chart rendering for the distance timeline.": "Dieser Plattform-Build enthält keine Diagrammdarstellung für die Distanz-Zeitachse.",
        "Insights Drilldown": "Insights-Drilldown",
        "Choose where to continue with this insight.": "Wähle, wie du mit diesem Insight fortfahren möchtest.",
        "Share": "Teilen",
        "Share Chart": "Diagramm teilen",
        "Share Failed": "Teilen fehlgeschlagen",
        "Chart sharing requires a newer Apple platform version.": "Das Teilen von Diagrammen benötigt eine neuere Apple-Plattformversion.",
        "The chart image could not be rendered on this device.": "Das Diagrammbild konnte auf diesem Gerät nicht gerendert werden.",
        "Export This Period": "Diesen Zeitraum exportieren",
        "No day matches the current drilldown and filter combination.": "Kein Tag passt zur aktuellen Drilldown- und Filter-Kombination.",
        "Need More Than One Day": "Mehr als ein Tag benötigt",
        "Daily averages become meaningful once the import contains at least two different days.": "Tagesdurchschnitte werden erst sinnvoll, wenn der Import mindestens zwei verschiedene Tage enthält.",
        "Activity Types": "Aktivitätstypen",
        "Compare activities by covered distance.": "Vergleiche Aktivitäten nach zurückgelegter Strecke.",
        "Compare activities by entry count.": "Vergleiche Aktivitäten nach Anzahl der Einträge.",
        "No Activity Breakdown": "Keine Aktivitätsaufschlüsselung",
        "No activity entries were found that could be summarized by type, distance or duration.": "Es wurden keine Aktivitätseinträge gefunden, die nach Typ, Distanz oder Dauer zusammengefasst werden könnten.",
        "Visit Types": "Besuchstypen",
        "No Visit Types": "Keine Besuchstypen",
        "This import does not contain visit data that can be grouped into semantic place types.": "Dieser Import enthält keine Besuchsdaten, die nach semantischen Ortstypen gruppiert werden können.",
        "By Day of Week": "Nach Wochentag",
        "Average visit and activity events per weekday across the imported days.": "Durchschnittliche Besuchs- und Aktivitätsereignisse pro Wochentag über die importierten Tage hinweg.",
        "Average recorded routes per weekday across the imported days.": "Durchschnittlich aufgezeichnete Routen pro Wochentag über die importierten Tage hinweg.",
        "Average visible route distance per weekday, using recorded trace geometry when imported route totals are missing.": "Durchschnittlich sichtbare Routendistanz pro Wochentag, mit Fallback auf aufgezeichnete Spur-Geometrie wenn importierte Routensummen fehlen.",
        "Need More Day Coverage": "Mehr Tagesabdeckung benötigt",
        "A weekday pattern is only shown once at least three separate day summaries are available.": "Ein Wochentagsmuster wird erst angezeigt, wenn mindestens drei getrennte Tageszusammenfassungen verfügbar sind.",
        "This platform build does not include chart rendering for the weekday view.": "Dieser Plattform-Build enthält keine Diagrammdarstellung für die Wochentagsansicht.",
        "Period Breakdown": "Periodenaufschlüsselung",
        "Compare how many imported days contribute to each visible period.": "Vergleiche, wie viele importierte Tage zu jeder sichtbaren Periode beitragen.",
        "Compare the combined visit, activity and route volume across visible periods.": "Vergleiche das kombinierte Besuchs-, Aktivitäts- und Routenvolumen über die sichtbaren Perioden hinweg.",
        "Compare visible route distance by period, using recorded trace geometry when imported route totals are missing.": "Vergleiche die sichtbare Routendistanz nach Periode, mit Fallback auf aufgezeichnete Spur-Geometrie wenn importierte Routensummen fehlen.",
        "No Period Stats": "Keine Periodenstatistiken",
        "This export does not include aggregated month or year period statistics.": "Dieser Export enthält keine aggregierten Monats- oder Jahresstatistiken.",
        "No Insights Yet": "Noch keine Einblicke",
        "This import contains no day entries, so there is nothing meaningful to analyze yet.": "Dieser Import enthält keine Tageinträge, daher gibt es noch nichts Sinnvolles zu analysieren.",
        "Limited Insight Data": "Begrenzte Einblicksdaten",
        "The import loaded correctly, but it does not contain enough structured data for the current insight views yet.": "Der Import wurde korrekt geladen, enthält aber noch nicht genügend strukturierte Daten für die aktuellen Einblick-Ansichten.",
        "Legend": "Legende",
        "Switch to standard map": "Zur Standardkarte wechseln",
        "Switch to satellite map": "Zur Satellitenkarte wechseln",
        "Completed live tracks are saved when you switch recording off. Background recording still depends on Always Allow permission and does not auto-resume after app relaunch.": "Abgeschlossene Live-Tracks werden gespeichert, wenn du Aufzeichnen ausschaltest. Hintergrundaufzeichnung hängt weiterhin von Always-Allow-Freigabe ab und startet nach dem App-Neustart nicht automatisch neu.",
        "Completed live tracks are saved when you switch recording off. No automatic resume runs after app relaunch.": "Abgeschlossene Live-Tracks werden gespeichert, wenn du Aufzeichnen ausschaltest. Nach dem App-Neustart gibt es kein automatisches Fortsetzen.",
        "Record a short local track, switch Record off, then open the Saved Tracks library to edit points, insert midpoints or delete a finished track.": "Nimm einen kurzen lokalen Track auf, schalte Aufzeichnen aus und öffne dann die Saved-Tracks-Mediathek, um Punkte zu bearbeiten, Mittelpunkte einzufügen oder einen fertigen Track zu löschen.",
        "Visit": "Besuch",
        "Distance": "Strecke",
        "Count": "Anzahl",
        "Activity Count": "Aktivitätsanzahl",
        "Visit Count": "Besuchsanzahl",
        "Day": "Tag",
        "Avg": "Durchschn.",
        "Avg events": "Durchschn. Ereignisse",
        "Local export filters are active": "Lokale Exportfilter sind aktiv",
        "Limit imported history by date window or maximum accuracy. Saved Live Tracks stay unaffected by these local export filters.": "Begrenze die importierte Historie nach Datumsfenster oder maximaler Genauigkeit. Gespeicherte Live-Tracks bleiben von diesen lokalen Exportfiltern unberührt.",
        "From": "Von",
        "To": "Bis",
        "Time Range": "Zeitraum",
        "All Time": "Gesamtzeitraum",
        "Last 7 Days": "Letzte 7 Tage",
        "Last 30 Days": "Letzte 30 Tage",
        "Last 90 Days": "Letzte 90 Tage",
        "This Year": "Dieses Jahr",
        "Custom Range": "Benutzerdefinierter Zeitraum",
        "Reset to All Time": "Auf Gesamtzeitraum zurücksetzen",
        "Showing the full imported time span.": "Der vollständige importierte Zeitraum wird angezeigt.",
        "Export always uses the active time range before any local export filters.": "Der Export verwendet immer zuerst den aktiven Zeitraum, bevor lokale Exportfilter angewendet werden.",
        "Start Date": "Startdatum",
        "End Date": "Enddatum",
        "Apply Range": "Zeitraum anwenden",
        "Cancel": "Abbrechen",
        "Select a custom date window.": "Wähle ein benutzerdefiniertes Datumsfenster aus.",
        "Start date must not be after the end date.": "Das Startdatum darf nicht nach dem Enddatum liegen.",
        "Choose a shorter date range.": "Wähle einen kürzeren Zeitraum.",
        "Choose a start date within the last 10 years.": "Wähle ein Startdatum innerhalb der letzten 10 Jahre.",
        "Any": "Beliebig",
        "Maximum accuracy": "Maximale Genauigkeit",
        "Required imported content": "Erforderlicher importierter Inhalt",
        "Activity types": "Aktivitätstypen",
        "Area": "Gebiet",
        "Area filter": "Gebietsfilter",
        "No Area Filter": "Kein Gebietsfilter",
        "Rectangle": "Rechteck",
        "Custom Shape": "Freie Form",
        "Area: Bounding box": "Gebiet: Begrenzungsrahmen",
        "Area: Polygon": "Gebiet: Polygon",
        "Area: Combined filters": "Gebiet: Kombinierte Filter",
        "Optional area filters affect imported history only. Saved Live Tracks always keep their full recorded geometry.": "Optionale Gebietsfilter betreffen nur die importierte Historie. Gespeicherte Live-Tracks behalten immer ihre vollständig aufgezeichnete Geometrie.",
        "Enter latitude and longitude bounds. Values are combined with any upstream export filters.": "Gib Breiten- und Längengrad-Grenzen ein. Die Werte werden mit vorhandenen Exportfiltern kombiniert.",
        "Min lat": "Min. Breite",
        "Max lat": "Max. Breite",
        "Min lon": "Min. Länge",
        "Max lon": "Max. Länge",
        "Enter one `lat,lon` pair per line. At least three vertices are required.": "Gib pro Zeile ein `Breite,Länge`-Paar ein. Mindestens drei Eckpunkte sind erforderlich.",
        "The current imported-history filters hide all day rows. Saved Live Tracks can still be exported separately.": "Die aktuellen Importhistorien-Filter blenden alle Tageszeilen aus. Gespeicherte Live-Tracks können weiterhin separat exportiert werden.",
        "Map preview requires a newer Apple platform version, but the export summary below still reflects the current selection.": "Die Kartenvorschau benötigt eine neuere Apple-Plattformversion, aber die Exportzusammenfassung unten spiegelt die aktuelle Auswahl weiterhin wider.",
        "The current selection has no routes with exportable geometry to preview.": "Die aktuelle Auswahl enthält keine Routen mit exportierbaren Verläufen für die Vorschau.",
        "Select content for export": "Inhalt für den Export auswählen",
        "The current selection contains no exportable route paths.": "Die aktuelle Auswahl enthält keine exportierbaren Routenverläufe.",
        "Foreground recording": "Vordergrundaufzeichnung",
        "Background recording": "Hintergrundaufzeichnung",
        "Server upload is enabled, but the URL is invalid.": "Server-Upload ist aktiviert, aber die URL ist ungültig.",
        "Approve while-using-the-app access to show your position and start recording.": "Erlaube Zugriff während der App-Nutzung, um deine Position anzuzeigen und die Aufzeichnung zu starten.",
        "Turn on live location to request foreground-only access.": "Aktiviere Live-Standort, um Zugriff nur im Vordergrund anzufordern.",
        "Location services are restricted on this device. Live recording stays unavailable.": "Die Ortungsdienste sind auf diesem Gerät eingeschränkt. Live-Aufzeichnung bleibt nicht verfügbar.",
        "Enable While Using the App access in Settings to show your position and record live tracks.": "Aktiviere in den Einstellungen Zugriff beim Verwenden der App, um deine Position anzuzeigen und Live-Tracks aufzuzeichnen.",
        "Background recording is enabled in Options, but Apple has only granted While Using the App so far. Approve Always Allow to keep recording when the app leaves the foreground.": "Hintergrundaufzeichnung ist in den Optionen aktiviert, aber Apple hat bisher nur Zugriff beim Verwenden der App gewährt. Erlaube Immer, damit die Aufzeichnung weiterläuft, wenn die App den Vordergrund verlässt.",
        "Recording did not start because Apple has not granted Always Allow yet. Enable Always in Settings or turn off background recording in Options.": "Die Aufzeichnung hat nicht gestartet, weil Apple bisher kein Immer erlauben gewährt hat. Aktiviere Immer in den Einstellungen oder deaktiviere die Hintergrundaufzeichnung in den Optionen.",
        "Recording can continue in the background and stays local to this app until you stop.": "Die Aufzeichnung kann im Hintergrund weiterlaufen und bleibt lokal in dieser App, bis du sie stoppst.",
        "Waiting for accurate foreground location updates.": "Warte auf genaue Standortaktualisierungen im Vordergrund.",
        "Recording stays local to this app and is saved only when you stop.": "Die Aufzeichnung bleibt lokal in dieser App und wird erst gespeichert, wenn du stoppst.",
        "Location is ready. Start recording to capture a live track and keep it running in the background when Always Allow is active.": "Der Standort ist bereit. Starte die Aufzeichnung, um einen Live-Track zu erfassen und ihn im Hintergrund weiterlaufen zu lassen, wenn Immer erlaubt aktiv ist.",
        "Foreground location is authorized. Start recording to show your position and begin a new live track.": "Vordergrund-Standortzugriff ist autorisiert. Starte die Aufzeichnung, um deine Position anzuzeigen und einen neuen Live-Track zu beginnen.",
        "The server returned HTTP %d.": "Der Server hat HTTP %d zurückgegeben."
        ,
        "OK": "OK",
        "Export Failed": "Export fehlgeschlagen",
        "No map content": "Kein Karteninhalt",
        "Selected": "Ausgewählt",
        "Not selected": "Nicht ausgewählt",
        "Latest saved track": "Zuletzt gespeicherter Track",
        "Edit Saved Track": "Gespeicherten Track bearbeiten",
        "This local track library is separate from imported history. Open any saved live track to edit points, insert midpoints or remove it from local storage.": "Diese lokale Track-Mediathek ist von der importierten Historie getrennt. Öffne einen gespeicherten Live-Track, um Punkte zu bearbeiten, Mittelpunkte einzufügen oder ihn aus dem lokalen Speicher zu entfernen.",
        "Live location and saved live tracks stay separate from the imported day data above.": "Live-Standort und gespeicherte Live-Tracks bleiben von den importierten Tagesdaten oben getrennt.",
        "Daily Averages": "Tagesdurchschnitte",
        "Visits / Day": "Besuche / Tag",
        "Activities / Day": "Aktivitäten / Tag",
        "Routes / Day": "Routen / Tag",
        "Distance / Day": "Strecke / Tag",
        "Type": "Typ",
        "Active Source": "Aktive Quelle",
        "Google Timeline": "Google Timeline",
        "No location history loaded": "Kein Standortverlauf geladen",
        "Recent Files": "Zuletzt verwendete Dateien",
        "Recently Used": "Zuletzt verwendet",
        "Show All": "Alle anzeigen",
        "Filter Days": "Tage filtern",
        "Days Search": "Tagessuche",
        "Combine chips with search while keeping the newest day first.": "Kombiniere Chips mit der Suche und behalte die neuesten Tage oben.",
        "Clear Filters": "Filter zurücksetzen",
        "Favorites": "Favoriten",
        "With Routes": "Mit Routen",
        "Has Visits": "Mit Besuchen",
        "Has Routes": "Mit Routen",
        "Has Distance": "Mit Strecke",
        "Exportable": "Exportierbar",
        "All Days": "Alle Tage",
        "No Matching Days": "Keine passenden Tage",
        "No days match \"%@\" with the current filters.": "Keine Tage passen mit den aktuellen Filtern zu \"%@\".",
        "No day matches the active filter chips.": "Kein Tag passt zu den aktiven Filterchips.",
        "No days fall within the selected date range. Change the range to see more days.": "Keine Tage liegen im ausgewählten Datumsbereich. Ändere den Zeitraum, um mehr Tage zu sehen.",
        "No days fall within the selected date range. Change the range above to see more days.": "Keine Tage liegen im ausgewählten Datumsbereich. Ändere den Zeitraum oben, um mehr Tage zu sehen.",
        "Add Favorite": "Favorit hinzufügen",
        "Remove Favorite": "Favorit entfernen",
        "Favorite": "Favorit",
        "Unfavorite": "Favorit entfernen",
        "Clear History": "Verlauf leeren",
        "Open Again": "Erneut öffnen",
        "Unavailable": "Nicht verfügbar",
        "Remove Entry": "Eintrag entfernen",
        "Available": "Verfügbar",
        "Opened": "Geöffnet",
        "Recent file unavailable": "Zuletzt verwendete Datei nicht verfügbar",
        "This recent file is no longer accessible. The entry was removed from history.": "Diese zuletzt verwendete Datei ist nicht mehr erreichbar. Der Eintrag wurde aus dem Verlauf entfernt.",
        "Unable to reopen recent file": "Zuletzt verwendete Datei konnte nicht erneut geöffnet werden",
        "Import the file again if it was moved, deleted or changed outside the app.": "Importiere die Datei erneut, wenn sie außerhalb der App verschoben, gelöscht oder verändert wurde.",
        "Restore Last Import on Launch": "Letzten Import beim Start wiederherstellen",
        "Imports": "Importe",
        "When enabled, the app tries to reopen the last imported file on startup. Missing or stale files are skipped automatically.": "Wenn aktiviert, versucht die App beim Start, die zuletzt importierte Datei erneut zu öffnen. Fehlende oder veraltete Dateien werden automatisch übersprungen.",
        "Day Actions": "Tagesaktionen",
        "Add Day to Export": "Tag zum Export hinzufügen",
        "Remove Day from Export": "Tag aus dem Export entfernen",
        "Route Export": "Routenexport",
        "Reset to All Routes": "Alle Routen wieder einschließen",
        "No exportable routes are available for this day.": "Für diesen Tag sind keine exportierbaren Routen verfügbar.",
        "Route unavailable for export": "Route nicht exportierbar",
        "This route has no exportable geometry.": "Diese Route hat keine exportierbare Geometrie.",
        "Unable to restore last import": "Letzter Import konnte nicht wiederhergestellt werden",
        "The last imported file could not be reopened automatically. Open a file manually to continue.": "Die zuletzt importierte Datei konnte nicht automatisch erneut geöffnet werden. Öffne manuell eine Datei, um fortzufahren.",
        "CSV always exports the visible table rows for visits, activities and routes.": "CSV exportiert immer die sichtbaren Tabellenzeilen für Besuche, Aktivitäten und Routen.",
        "Open an LH2GPX app_export.json or .zip from the LocationHistory2GPX tool, or a Google Timeline location-history.json or .zip. Demo data is available as a fallback.": "Öffne eine LH2GPX-app_export.json oder .zip aus dem LocationHistory2GPX-Tool oder eine Google-Timeline-location-history.json bzw. .zip. Demodaten stehen als Fallback bereit.",
        "Opening location history": "Standortverlauf wird geöffnet",
        "Pending": "Ausstehend",
        "Processing location history data.": "Standortverlaufsdaten werden verarbeitet.",
        "Demo data loaded": "Demodaten geladen",
        "Demo fixture": "Demo-Datei",
        "Bundled demo data is active. Open a local location history file to replace it.": "Gebündelte Demodaten sind aktiv. Öffne eine lokale Standortverlaufsdatei, um sie zu ersetzen.",
        "Bundled demo data decoded successfully but does not contain any day entries.": "Die gebündelten Demodaten wurden erfolgreich dekodiert, enthalten aber keine Tageinträge.",
        "Location history loaded": "Standortverlauf geladen",
        "Imported file": "Importierte Datei",
        "Local file content is active. Open another file to replace it.": "Der Inhalt der lokalen Datei ist aktiv. Öffne eine andere Datei, um ihn zu ersetzen.",
        "The file was decoded successfully but does not contain any day entries.": "Die Datei wurde erfolgreich dekodiert, enthält aber keine Tageinträge.",
        "Unable to open location history": "Standortverlauf konnte nicht geöffnet werden",
        "No location history is currently active. Open a local location history file or load demo data.": "Aktuell ist kein Standortverlauf aktiv. Öffne eine lokale Standortverlaufsdatei oder lade Demodaten.",
        "Last loaded content remains visible": "Zuletzt geladener Inhalt bleibt sichtbar",
        "Current content": "Aktueller Inhalt",
        "The last successfully loaded content remains visible. Open another file to replace it or Clear to reset.": "Der zuletzt erfolgreich geladene Inhalt bleibt sichtbar. Öffne eine andere Datei, um ihn zu ersetzen, oder nutze Leeren zum Zurücksetzen.",
        "Demo data ready": "Demodaten bereit",
        "Location history ready": "Standortverlauf bereit",
        "Open a local location history file or load the bundled demo data.": "Öffne eine lokale Standortverlaufsdatei oder lade die gebündelten Demodaten."
        ,
        "GPS Exchange Format – compatible with most navigation and mapping apps.": "GPS Exchange Format – kompatibel mit den meisten Navigations- und Karten-Apps.",
        "KMZ": "KMZ",
        "KMZ Archive – a zipped KML compatible with Google Earth and mapping apps.": "KMZ-Archiv – eine gepackte KML-Datei für Google Earth und andere Karten-Apps.",
        "KMZ export failed. The archive could not be created.": "KMZ-Export fehlgeschlagen. Das Archiv konnte nicht erstellt werden.",
        "Keyhole Markup Language – useful for Google Earth and other map viewers.": "Keyhole Markup Language – nützlich für Google Earth und andere Kartenbetrachter.",
        "GeoJSON FeatureCollection – useful for browsers, GIS tools, and developer workflows.": "GeoJSON-FeatureCollection – nützlich für Browser, GIS-Werkzeuge und Entwickler-Workflows.",
        "Tracks": "Tracks",
        "Waypoints": "Wegpunkte",
        "Both": "Beides",
        "Double-tap to toggle selection": "Doppeltippen zum Umschalten der Auswahl",
        "No data": "Keine Daten",
        "Replace the current import with another local file.": "Ersetze den aktuellen Import durch eine andere lokale Datei.",
        "Jump into the day list and open imported history entries.": "Wechsle zur Tagesliste und öffne importierte Historieneinträge.",
        "Switch to charts and derived breakdowns for the current import.": "Wechsle zu Diagrammen und Aufschlüsselungen für den aktuellen Import.",
        "Choose days and prepare a GPX export from recorded routes.": "Wähle Tage aus und bereite einen GPX-Export aus aufgezeichneten Routen vor.",
        "Open the separate local track library and edit finished recordings there.": "Öffne die separate lokale Track-Bibliothek und bearbeite dort fertige Aufzeichnungen.",
        "Visualize your movement density on a map.": "Visualisiere deine Bewegungsdichte auf einer Karte.",
        "Open the export sheet for the current imported history.": "Öffne das Export-Fenster für den aktuell importierten Verlauf.",
        "Heatmap": "Heatmap",
        "Toggle map style": "Kartenstil umschalten",
        "Fit to data": "Auf Daten zoomen",
        "Controls affect display only.": "Regler beeinflussen nur die Darstellung.",
        "Opacity": "Deckkraft",
        "Radius": "Radius",
        "Low density": "Niedrige Dichte",
        "High density": "Hohe Dichte",
        "Compact": "Kompakt",
        "Wide": "Breit",
        "Density": "Dichte",
        "Activity": "Aktivität",
        "Speed": "Tempo",
        "Speed colours": "Tempo-Farben",
        "Viridis": "Viridis",
        "Track Colour": "Layer",
        "Layer": "Layer",
        "Show accuracy circle": "Genauigkeitsradius anzeigen",
        "Pulsing live dot": "Pulsierender Live-Punkt",
        "Fade older breadcrumbs": "Ältere Spur ausblenden",
        "Palette": "Palette",
        "Scale": "Skala",
        "Logarithmic": "Logarithmisch",
        "Linear": "Linear",
        "Magma": "Magma",
        "Inferno": "Inferno",
        "Cividis": "Cividis",
        "points": "Punkte",
        "day": "Tag",
        "days": "Tage",
        "Expand controls": "Regler einblenden",
        "Collapse controls": "Regler einklappen",
        "Saved live tracks live in a separate local library. Record a short track on any day, then open it from here.": "Gespeicherte Live-Tracks liegen in einer separaten lokalen Bibliothek. Nimm einen kurzen Track an einem beliebigen Tag auf und öffne ihn von hier aus.",
        "Open the local track library directly from Overview to edit points, insert midpoints or delete a saved live track.": "Öffne die lokale Track-Bibliothek direkt aus der Übersicht, um Punkte zu bearbeiten, Mittelpunkte einzufügen oder einen gespeicherten Live-Track zu löschen.",
        "Live": "Live",
        "Live Tracking": "Live-Tracking",
        "Live Map": "Live-Karte",
        "Recording": "Aufzeichnung",
        "Idle": "Bereit",
        "Foreground Only": "Nur Vordergrund",
        "Background Ready": "Hintergrund bereit",
        "Upload": "Upload",
        "Advanced": "Erweitert",
        "Track Library": "Track-Mediathek",
        "Patterns": "Muster",
        "Breakdowns": "Aufschlüsselungen",
        "Start Recording": "Aufzeichnung starten",
        "Stop Recording": "Aufzeichnung stoppen",
        "Center": "Zentrieren",
        "Center Map": "Karte zentrieren",
        "Upload Guidance": "Upload-Hinweis",
        "Latest Upload Status": "Letzter Upload-Status",
        "Invalid endpoint": "Ungültiger Endpunkt",
        "Uploading": "Lädt hoch",
        "Paused": "Pausiert",
        "Needs retry": "Wartet auf Wiederholung",
        "Queue pending": "Warteschlange offen",
        "Ready": "Bereit",
        "Endpoint": "Endpunkt",
        "Auth": "Authentifizierung",
        "Batch Size": "Batch-Größe",
        "Queue": "Warteschlange",
        "Failures": "Fehler",
        "Last Success": "Letzter Erfolg",
        "No token": "Kein Token",
        "Token set": "Token gesetzt",
        "Pause Uploads": "Uploads pausieren",
        "Resume Uploads": "Uploads fortsetzen",
        "Flush Queue": "Warteschlange senden",
        "Queued Point": "Wartender Punkt",
        "Queued Points": "Wartende Punkte",
        "Location not available": "Standort nicht verfügbar",
        "Current Speed": "Aktuelle Geschwindigkeit",
        "Average Speed": "Durchschnittsgeschwindigkeit",
        "Last Segment": "Letztes Segment",
        "Update Age": "Alter des Updates",
        "Last Fix": "Letzter Fix",
        "Monthly Trends": "Monatstrends",
        "Top Days": "Top-Tage",
        "No Monthly Trend Yet": "Noch kein Monatstrend",
        "At least one month with visible days is required before this trend becomes meaningful.": "Mindestens ein Monat mit sichtbaren Tagen ist nötig, bevor dieser Trend sinnvoll wird.",
        "Insights Overview": "Einblicke-Übersicht",
        "Days Loaded": "Geladene Tage",
        "Average Distance / Day": "Durchschnittsstrecke / Tag",
        "Across visible days": "Über sichtbare Tage hinweg",
        "Active Months": "Aktive Monate",
        "Months with visible day entries": "Monate mit sichtbaren Tageinträgen",
        "Imported route distance": "Importierte Routendistanz",
        "Route distance with trace fallback": "Routendistanz mit Spur-Fallback",
        "Most Visits": "Meiste Besuche",
        "Most Routes": "Meiste Routen",
        "No Ranked Days Yet": "Noch keine Rangliste möglich",
        "Visible day summaries need at least one visit, route or distance signal before they can be ranked.": "Sichtbare Tageszusammenfassungen brauchen mindestens ein Besuchs-, Routen- oder Distanzsignal, bevor sie gerankt werden können.",
        "Switch between a concise overview, recurring patterns and deeper breakdowns without leaving the current import.": "Wechsle zwischen kompakter Übersicht, wiederkehrenden Mustern und tieferen Aufschlüsselungen, ohne den aktuellen Import zu verlassen.",
        "Spot month-to-month changes in visible route distance, visits, routes or total activity volume.": "Erkenne Monatsveränderungen bei sichtbarer Routendistanz, Besuchen, Routen oder gesamtem Aktivitätsvolumen.",
        "Active Filters": "Aktive Filter",
        "Month": "Monat",
        "Events": "Ereignisse",
        "Visits": "Besuche",
        "Routes": "Routen",
        "Period": "Periode",
        "Avg routes": "Durchschn. Routen",
        "A live session is running. The map follows the latest accepted points and current foreground fix.": "Eine Live-Sitzung läuft. Die Karte folgt den zuletzt akzeptierten Punkten und dem aktuellen Vordergrund-Fix.",
        "Live location is ready. Start a recording or inspect the current fix before you move.": "Live-Standort ist bereit. Starte eine Aufzeichnung oder prüfe den aktuellen Fix, bevor du dich bewegst.",
        "Recording must start once before the app can request foreground location access.": "Die Aufzeichnung muss einmal gestartet werden, bevor die App Standortzugriff im Vordergrund anfordern kann.",
        "Current fix quality, movement speed and queue health update continuously while recording stays active.": "Fixqualität, Bewegungsgeschwindigkeit und Warteschlangenstatus aktualisieren sich laufend, solange die Aufzeichnung aktiv ist.",
        "Start locally, then optionally forward accepted points to your own HTTPS endpoint.": "Starte lokal und leite akzeptierte Punkte optional an deinen eigenen HTTPS-Endpunkt weiter.",
        "Finish the current local track and keep queued uploads ready.": "Beende den aktuellen lokalen Track und halte wartende Uploads bereit.",
        "Begin a new local recording session with the current live settings.": "Beginne eine neue lokale Aufzeichnungssitzung mit den aktuellen Live-Einstellungen.",
        "Review endpoint health, queue pressure and retry state for optional server forwarding.": "Prüfe Endpunktzustand, Warteschlangendruck und Wiederholungsstatus für das optionale Weiterleiten an den Server.",
        "Uploads are paused until you resume them.": "Uploads bleiben pausiert, bis du sie fortsetzt.",
        "Uploads are paused. Resume or flush manually to send queued points.": "Uploads sind pausiert. Setze sie fort oder sende die Warteschlange manuell.",
        "Retry runs on the next accepted point, or you can flush the queue manually.": "Die Wiederholung läuft mit dem nächsten akzeptierten Punkt oder per manuellem Senden der Warteschlange.",
        "Server upload is ready.": "Server-Upload ist bereit.",
        "Server upload is ready. No bearer token is configured.": "Server-Upload ist bereit. Es ist kein Bearer-Token konfiguriert.",
        "Queued points wait until the configured batch size is reached.": "Wartende Punkte bleiben liegen, bis die konfigurierte Batch-Größe erreicht ist.",
        "No queued points to upload.": "Es gibt keine wartenden Punkte zum Hochladen.",
        "Server upload paused.": "Server-Upload pausiert.",
        "Record a short route and stop it once to seed the local track library.": "Nimm eine kurze Strecke auf und stoppe sie einmal, um die lokale Track-Mediathek zu füllen.",
        "Local recordings stay separate from imported history until you open them for editing or export.": "Lokale Aufzeichnungen bleiben von der importierten Historie getrennt, bis du sie zum Bearbeiten oder Exportieren öffnest.",
        "Permission state, background preference and local capture rules remain visible here.": "Berechtigungsstatus, Hintergrundpräferenz und lokale Aufnahme-Regeln bleiben hier sichtbar.",
        "No saved tracks yet": "Noch keine gespeicherten Tracks",
        "Open Track Library": "Track-Mediathek öffnen",
        // Overview + Insights polish strings
        "Overview, Patterns and Breakdowns for your imported history.": "Übersicht, Muster und Aufschlüsselungen für deine importierte Historie.",
        "Total route distance": "Gesamte Routendistanz",
        "Daily average": "Tagesschnitt",
        "Months with activity": "Monate mit Aktivität",
        "All Time Selected": "Gesamter Zeitraum ausgewählt",
        "Period comparison is not available for All Time. Select a specific date range to compare periods.": "Periodenvergleich ist für den gesamten Zeitraum nicht verfügbar. Wähle einen bestimmten Datumsbereich, um Perioden zu vergleichen.",
        "Select Last 7 Days, Last 30 Days or a custom range to enable the comparison.": "Wähle Letzte 7 Tage, Letzte 30 Tage oder einen eigenen Bereich, um den Vergleich zu aktivieren.",
        "At least 2 days are needed for a streak.": "Mindestens 2 Tage werden für eine Streak benötigt.",
        "No days with activity found in the selected range.": "Keine Tage mit Aktivität im ausgewählten Bereich gefunden.",
        // Favorites toggle in overview (task 2)
        "Favorites Only": "Nur Favoriten",
        "Showing favorites only. Tap to show all days.": "Zeigt nur Favoriten. Tippe, um alle Tage anzuzeigen.",
        "Showing all days. Tap to show favorites only.": "Zeigt alle Tage. Tippe, um nur Favoriten anzuzeigen.",
        // Overview tracks map (task 3)
        "No tracks in selected range": "Keine Tracks im ausgewählten Zeitraum",
        "Loading map…": "Karte wird geladen…",
        "Analysing routes…": "Routen werden analysiert…",
        "Building map…": "Karte wird aufgebaut…",
        "Explore": "Erkunden",
        "Optimized overview": "Optimierte Übersicht",
        "Simplified map – export complete": "Karte vereinfacht – Export vollständig",
        "Simplified preview · export complete": "Vereinfachte Vorschau · Export vollständig",
        "route": "Route",
        "routes": "Routen",
        "Overview map with": "Übersichtskarte mit",
        // Heatmap chip (task 4)
        "Computing heatmap…": "Heatmap wird berechnet…",
        // Insights strings missing DE
        "No activity streak yet. Start recording to build your streak.": "Noch keine Aktivitätsserie. Starte die Aufzeichnung, um deine Serie aufzubauen.",
        "Comparing the active date range to the equal-length period immediately before it.": "Vergleicht den aktiven Datumsbereich mit dem gleich langen Zeitraum unmittelbar davor.",
        "No data available for this period.": "Keine Daten für diesen Zeitraum verfügbar.",
        "No days with recorded routes in the selected range.": "Keine Tage mit aufgezeichneten Routen im ausgewählten Zeitraum.",
        // Accessibility strings
        "Date Range": "Datumsbereich",
        "Tap to change.": "Tippen zum Ändern.",
        "All Days. Tap to filter by date range.": "Alle Tage. Tippen, um nach Datumsbereich zu filtern.",
        "Clear Date Range": "Datumsbereich löschen",
        // Landscape / general missing strings
        "No Days in Range": "Keine Tage im Zeitraum",
        "Ranked by total visits, activities and routes.": "Gerankt nach Besuchen, Aktivitäten und Routen gesamt.",
        "Ranked by semantic visit count.": "Gerankt nach semantischer Besuchszahl.",
        "Ranked by recorded route count.": "Gerankt nach Anzahl aufgezeichneter Routen.",
        "Ranked by total route distance.": "Gerankt nach Gesamtroutendistanz.",
        "Tap a row to open drilldown actions for that day.": "Tippe eine Zeile, um Drilldown-Aktionen für diesen Tag zu öffnen.",
        "Saved Live Tracks Unavailable": "Gespeicherte Live-Tracks nicht verfügbar",
        "Days with tracked activity": "Tage mit aufgezeichneter Aktivität",
        "Map": "Karte",
        "Active Days": "Aktive Tage",
        "Places": "Orte",
        "Most Activities": "Meiste Aktivitäten",
        "Show All Insights": "Alle Insights anzeigen",
        "Continue": "Weiterarbeiten",
        "Prepare Export": "Export vorbereiten",
        "Import New File": "Neue Datei importieren",
        "Live Activities are available for active recordings on this device.": "Live-Aktivitäten sind für aktive Aufzeichnungen auf diesem Gerät verfügbar.",
        "Live Activities are turned off in iOS Settings for this device.": "Live-Aktivitäten sind in den iOS-Einstellungen auf diesem Gerät deaktiviert.",
        "Live Activities require iPhone with iOS 16.2 or later.": "Live-Aktivitäten benötigen ein iPhone mit iOS 16.2 oder neuer.",
        // GPX / TCX import strings
        "GPX file": "GPX-Datei",
        "TCX file": "TCX-Datei",
        "GPS Exchange Format": "GPS Exchange Format",
        "Training Center XML": "Training Center XML",
        "GPX imported": "GPX importiert",
        "TCX imported": "TCX importiert",
        "File contains no track points": "Datei enthält keine Trackpunkte",
        // Day path display mode (Phase B1)
        "Original": "Original",
        "Simplified": "Vereinfacht",
        "Route Display": "Routen-Darstellung",
        // Google Maps Export Help (Prompt 4)
        "Google Maps Export on iPhone": "Google Maps Export auf iPhone",
        "Google Maps Export Guide": "Google Maps Export-Anleitung",
        "Google Maps export help": "Hilfe: Google Maps Export",
        "Open Heatmap": "Heatmap öffnen",
        "Open Google Maps on your iPhone.": "Öffne Google Maps auf deinem iPhone.",
        "Tap your profile picture and open Settings.": "Tippe auf dein Profilbild und öffne Einstellungen.",
        "Open \u{201C}Location & Privacy\u{201D} and select \u{201C}Export Timeline data\u{201D}.": "\u{201E}Standort und Datenschutz\u{201C} öffnen und \u{201E}Timeline-Daten exportieren\u{201C} wählen.",
        "Save the file to \u{201C}Files\u{201D}, then open it here in LH2GPX.": "Datei in \u{201E}Dateien\u{201C} speichern, dann hier in LH2GPX öffnen.",
        "If the direct export is unavailable, a Google Takeout export may be required depending on your account.": "Falls der direkte Export nicht verfügbar ist, kann je nach Google-Konto alternativ ein Google-Takeout-Export nötig sein.",
        "Dismiss help": "Hilfe schließen",
        "Step": "Schritt",
        "Opens step-by-step export instructions": "Öffnet Schritt-für-Schritt-Exportanleitung",
        // Interrupted session banner — Live Tracking
        "Recording interrupted": "Aufzeichnung unterbrochen",
        "A recording was interrupted. Start a new session?": "Eine Aufzeichnung wurde unterbrochen. Neue Sitzung starten?",
        "A recording started %@ was interrupted. Start a new session?": "Eine Aufzeichnung, die %@ gestartet wurde, wurde unterbrochen. Neue Sitzung starten?",
        "Resume recording": "Aufzeichnung fortsetzen",
        "Ignore": "Ignorieren",
        "Disable follow mode": "Folgemodus deaktivieren",
        "Enable follow mode": "Folgemodus aktivieren",
        "Open fullscreen map": "Karte im Vollbild öffnen",
        "Close fullscreen map": "Vollbild-Karte schließen",
        "Fullscreen": "Vollbild",
        "GPS Accuracy": "GPS-Genauigkeit",
        "Duration": "Dauer",
        "The widget updates automatically after each recording. The selected Dynamic Island value is shown in compact and expanded Live Activity regions during active recording.": "Das Widget aktualisiert sich nach jeder Aufzeichnung automatisch. Der ausgewählte Dynamic-Island-Wert wird während aktiver Aufzeichnungen in den kompakten und erweiterten Live-Activity-Bereichen angezeigt.",
        "Session": "Sitzung",
        "Start recording to request location access and see your position here.": "Starte die Aufzeichnung, um Standortzugriff anzufordern und deine Position hier zu sehen.",
        "Background Recording": "Hintergrundaufzeichnung",
        // Imported-path deletion (History Track Editor)
        "Remove Route": "Route entfernen",
        "Remove": "Entfernen",
        "This route will be hidden from this day. The original data is not modified.": "Diese Route wird für diesen Tag ausgeblendet. Die Originaldaten bleiben unverändert.",
        // LHCollapsibleMapHeader / LHContextBar
        "Show Technical Details": "Technische Details anzeigen",
        "Show Map": "Karte anzeigen",
        "Collapse Map": "Karte einklappen",
        "Expand Map": "Karte erweitern",
        "Close Map": "Karte schließen",
        "Dismiss": "Schließen",
        // Insights Dashboard Redesign
        "Open in Days": "In Tage öffnen",
        "Select for Export": "Für Export auswählen",
        "Show on Map": "Auf Karte zeigen",
        "Activity Overview": "Aktivitätsübersicht",
        "Activity Streak": "Aktivitätsserie",
        "Period Comparison": "Periodenvergleich",
        "Import More Data": "Mehr Daten importieren",
        // Live Tracking Redesign Batch 5A
        "Diagnostics": "Diagnose",
        "Ready to Record": "Bereit zur Aufzeichnung",
        "Requesting Permission": "Berechtigung wird angefordert",
        "Not Started": "Nicht gestartet",
        "Location is being tracked and saved locally.": "Standort wird aufgezeichnet und lokal gespeichert.",
        "Waiting for location access approval.": "Warte auf Bestätigung des Standortzugriffs.",
        "Update location permissions in Settings to start recording.": "Standortberechtigung in Einstellungen anpassen, um die Aufzeichnung zu starten.",
        "Tap Start Recording to begin a new live track.": "Tippe auf 'Aufzeichnung starten', um einen neuen Live-Track zu beginnen.",
        "Tap Start Recording to request location access.": "Tippe auf 'Aufzeichnung starten', um Standortzugriff anzufordern.",
        "Live recording metrics, GPS accuracy and update statistics.": "Aufzeichnungsmetriken, GPS-Genauigkeit und Aktualisierungsstatistiken.",
        "Tap to view recording metrics and GPS details.": "Antippen für Aufzeichnungsmetriken und GPS-Details.",
        // Insights Dashboard Redesign Batch 4
        "active day": "aktiver Tag",
        "active days": "aktive Tage",
        "No days match the current filter. Adjust the range or reset it to see insights.": "Keine Tage passen zum aktuellen Filter. Passe den Zeitraum an oder setze ihn zurück.",
        "Reset Filter": "Filter zurücksetzen",
        // Export Checkout Redesign
        "Selection": "Auswahl",
        "Content": "Inhalt",
        "Edit Selection": "Auswahl bearbeiten",
        "Export Format": "Exportformat",
        "Advanced Filters": "Erweiterte Filter",
        "No exportable data selected": "Keine exportierbaren Daten ausgewählt",
        "No exportable routes selected": "Keine exportierbaren Routen ausgewählt",
        "No exportable content selected": "Kein exportierbarer Inhalt ausgewählt",
        "No waypoints in selection": "Keine Wegpunkte in der Auswahl",
        "Reset Drilldown": "Drilldown zurücksetzen",
        "Adopted from Insights": "Aus Insights übernommen",
        "Live Tracks": "Live-Tracks",
        "Tracks + Waypoints": "Tracks + Wegpunkte",
        // Live Tracking Redesign
        "GPS Good": "GPS gut",
        "GPS Weak": "GPS schwach",
        "GPS Searching": "GPS-Suche",
        "Upload Active": "Upload aktiv",
        "Upload Off": "Upload aus",
        "Upload Waiting": "Upload wartet",
        "View All Live Tracks": "Alle Live-Tracks anzeigen",
        "New Track": "Neuer Track",
        "Stored Locally": "Lokal gespeichert",
        "Separate from imported history": "Getrennt von importierter Historie",
        "Follow On": "Folgen aktiv",
        "Follow Off": "Folgen aus",
        "Recording Active": "Aufzeichnung läuft",
        // Options + Widget/Live-Activity Redesign
        "General": "Allgemein",
        "Live Recording": "Live-Aufzeichnung",
        "Battery": "Akku sparen",
        "Precise": "Präzise",
        "Custom": "Benutzerdefiniert",
        "High-Accuracy Location": "Hochpräzise Standortdaten",
        "Motion Filter": "Bewegungsfilter",
        "Update Interval": "Aktualisierungsintervall",
        "Minimum Distance Filter": "Minimum-Distanzfilter",
        "Recording Preset": "Aufnahme-Voreinstellung",
        "Settings": "Einstellungen",
        "Upload URL": "Upload-URL",
        "Bearer Token": "Bearer-Token",
        "Token saved": "Token gespeichert",
        "Token not set": "Token nicht gesetzt",
        "Dynamic Island Primary Value": "Dynamic-Island-Primärwert",
        "Home Widget": "Home Widget",
        "Active only during recording": "Nur während laufender Aufnahme",
        "Fallback active": "Fallback aktiv",
        "Dynamic Island": "Dynamic Island",
        "Points per Batch": "Punkte pro Batch",
        "Advanced settings active. Choosing a preset will overwrite current values.": "Erweiterte Einstellungen aktiv. Wechsel auf ein Preset überschreibt aktuelle Werte.",
        "Display, language and import options": "Anzeige, Sprache und Importoptionen",
        "Default style for all map views": "Standardstil für alle Kartenansichten",
        "Auto-restore and import behaviour": "Automatische Wiederherstellung und Importverhalten",
        "Accuracy, interval and background recording": "Genauigkeit, Intervall und Hintergrundaufzeichnung",
        "Optional self-hosted upload (off by default)": "Optionaler Upload, selbst gehostet (standardmäßig aus)",
        "Dynamic Island value and home widget": "Dynamic-Island-Wert und Home Widget",
        "Storage location and optional upload disclosure": "Speicherort und optionaler Upload-Hinweis",
        "Reset all options to defaults": "Alle Optionen zurücksetzen",
        "Resets all app preferences to their default values. Live tracks and imported data are not affected.": "Setzt alle App-Einstellungen auf Standardwerte zurück. Live-Tracks und importierte Daten bleiben unverändert.",
        "The widget updates automatically after each recording.": "Das Widget aktualisiert sich nach jeder Aufzeichnung automatisch.",
        // Options truth-sync: missing strings discovered 2026-05-01
        "Invalid URL": "Ungültige URL",
        "Automatic Widget Update": "Automatisches Widget-Update",
        "Widget & Live Activity": "Widget & Live-Activity",
        "Live Activity": "Live-Activity",
        "Reachable": "Erreichbar",
        "Unreachable": "Nicht erreichbar",
        "Test Connection": "Verbindung testen",
        "Testing…": "Testen…",
        "Last tour + weekly status": "Letzte Tour + Wochenstatus"
    ]
}
