import Foundation

public enum AppLanguagePreference: String, CaseIterable, Identifiable {
    case english
    case german

    public var id: String { rawValue }
    public var isGerman: Bool { self == .german }

    public var title: String {
        switch self {
        case .english:
            return "English"
        case .german:
            return "Deutsch"
        }
    }

    public var locale: Locale {
        switch self {
        case .english:
            return Locale(identifier: "en")
        case .german:
            return Locale(identifier: "de")
        }
    }

    public func localized(_ english: String) -> String {
        switch self {
        case .english:
            return english
        case .german:
            return AppGermanTranslations.values[english] ?? english
        }
    }

    public func localized(format englishFormat: String, arguments: [CVarArg]) -> String {
        let format = localized(englishFormat)
        return String(format: format, locale: locale, arguments: arguments)
    }
}

enum AppGermanTranslations {
    static let values: [String: String] = [
        "Overview": "Übersicht",
        "Days": "Tage",
        "Insights": "Einblicke",
        "Export": "Export",
        "Options": "Optionen",
        "Actions": "Aktionen",
        "Clear": "Leeren",
        "Done": "Fertig",
        "Saved Live Tracks": "Gespeicherte Live-Tracks",
        "Open Library": "Mediathek öffnen",
        "No Results": "Keine Treffer",
        "Primary Actions": "Wichtige Aktionen",
        "Browse Days": "Tage ansehen",
        "Open Insights": "Einblicke öffnen",
        "Export GPX": "GPX exportieren",
        "Highlights": "Highlights",
        "Busiest Day": "Aktivster Tag",
        "Longest Distance": "Längste Strecke",
        "Total Distance": "Gesamtstrecke",
        "Filtered Export": "Gefilterter Export",
        "No Insights Available": "Keine Einblicke verfügbar",
        "Load a location history file to see detailed insights.": "Lade eine Standortverlauf-Datei, um detaillierte Einblicke zu sehen.",
        "Select a day from the list to view details.": "Wähle einen Tag aus der Liste, um Details zu sehen.",
        "Back to Overview": "Zurück zur Übersicht",
        "Local Recording": "Lokale Aufzeichnung",
        "Current position and saved live tracks stay separate from imported history.": "Aktuelle Position und gespeicherte Live-Tracks bleiben von importierter Historie getrennt.",
        "Record": "Aufzeichnen",
        "Record live track": "Live-Track aufzeichnen",
        "Current Location": "Aktueller Standort",
        "Center on current location": "Auf aktuellen Standort zentrieren",
        "Live location is off": "Live-Standort ist aus",
        "Turn recording on to request foreground-only location access and draw a live track.": "Aktiviere die Aufzeichnung, um Standortzugriff im Vordergrund anzufordern und einen Live-Track zu zeichnen.",
        "Distance Units": "Entfernungseinheiten",
        "Start Tab": "Start-Tab",
        "Show Technical Import Details": "Technische Importdetails anzeigen",
        "Display": "Anzeige",
        "Controls how much metadata the app shows around imports and source information.": "Steuert, wie viele Metadaten die App rund um Importe und Quelleninformationen anzeigt.",
        "Default Map Style": "Standard-Kartenstil",
        "Maps": "Karten",
        "Applies to the day-detail map and live-location map.": "Gilt für die Tagesdetail-Karte und die Live-Standort-Karte.",
        "Accuracy Filter": "Genauigkeitsfilter",
        "Recording Detail": "Aufzeichnungsdetail",
        "Allow Background Recording": "Hintergrundaufzeichnung erlauben",
        "Accepted Accuracy": "Akzeptierte Genauigkeit",
        "Minimum Movement": "Mindestbewegung",
        "Minimum Time Gap": "Minimaler Zeitabstand",
        "Server Upload": "Server-Upload",
        "Language": "Sprache",
        "Upload to Custom Server": "An eigenen Server senden",
        "Server URL": "Server-URL",
        "Bearer Token (optional)": "Bearer-Token (optional)",
        "Language and Upload": "Sprache und Upload",
        "Choose the app language and optionally forward accepted live-recording points to your own endpoint. Upload stays off until a valid URL is present.": "Wähle die App-Sprache und leite akzeptierte Live-Aufzeichnungspunkte optional an deinen eigenen Endpunkt weiter. Der Upload bleibt aus, bis eine gültige URL vorhanden ist.",
        "Privacy": "Datenschutz",
        "Location Data": "Standortdaten",
        "Stored locally on this device": "Lokal auf diesem Gerät gespeichert",
        "Foreground + optional background": "Vordergrund + optional Hintergrund",
        "Foreground only": "Nur Vordergrund",
        "This app keeps imports and live tracks local by default. Server upload is optional, user-controlled and only sends accepted live-recording points to the configured endpoint.": "Diese App hält Importe und Live-Tracks standardmäßig lokal. Server-Upload ist optional, nutzergesteuert und sendet nur akzeptierte Live-Aufzeichnungspunkte an den konfigurierten Endpunkt.",
        "Technical": "Technisch",
        "Reset Options": "Optionen zurücksetzen",
        "Kilometers": "Kilometer",
        "Miles": "Meilen",
        "Standard": "Standard",
        "Satellite Hybrid": "Satellit Hybrid",
        "Relaxed": "Locker",
        "Balanced": "Ausgewogen",
        "Strict": "Strikt",
        "Battery Saver": "Batteriesparer",
        "Detailed": "Detailliert",
        "Waiting for Location Permission": "Warte auf Standortfreigabe",
        "Location Permission Not Requested": "Standortfreigabe nicht angefordert",
        "Location Access Restricted": "Standortzugriff eingeschränkt",
        "Location Access Denied": "Standortzugriff verweigert",
        "Recording in Background": "Aufzeichnung im Hintergrund",
        "Background Upgrade Pending": "Hintergrundfreigabe ausstehend",
        "Recording Live Track": "Live-Track wird aufgezeichnet",
        "Live Location Ready": "Live-Standort bereit",
        "Search by date": "Nach Datum suchen",
        "Search by date, weekday or month": "Nach Datum, Wochentag oder Monat suchen",
        "This app currently has no cloud sync and no server transfer. Background recording remains local to this device and still depends on Apple location permission.": "Diese App hat derzeit keine Cloud-Synchronisierung und keinen Servertransfer. Hintergrundaufzeichnung bleibt lokal auf diesem Gerät und hängt weiterhin von Apples Standortfreigabe ab.",
        "English": "Englisch",
        "Accepts up to 100 m accuracy.": "Akzeptiert bis zu 100 m Genauigkeit.",
        "Accepts up to 65 m accuracy.": "Akzeptiert bis zu 65 m Genauigkeit.",
        "Accepts up to 25 m accuracy.": "Akzeptiert bis zu 25 m Genauigkeit.",
        "Fewer stored points, larger movement threshold.": "Weniger gespeicherte Punkte, höherer Bewegungs-Schwellwert.",
        "Default spacing for local live tracks.": "Standardabstand für lokale Live-Tracks.",
        "Keeps more movement detail with tighter thresholds.": "Behält mehr Bewegungsdetails mit engeren Schwellwerten.",
        "App Language": "App-Sprache",
        "Test Endpoint": "Test-Endpunkt",
        "Accepted live-recording points only. Use an HTTP(S) endpoint you control. The default test endpoint is prefilled with this server IP and can be changed at any time.": "Nur akzeptierte Live-Aufzeichnungspunkte. Nutze einen HTTP(S)-Endpunkt unter deiner Kontrolle. Der Standard-Testendpunkt ist mit der IP dieses Servers vorbefüllt und kann jederzeit geändert werden.",
        "Enabled": "Aktiv",
        "Disabled": "Deaktiviert",
        "Enabled (invalid URL)": "Aktiv (ungültige URL)",
        "Upload status": "Upload-Status",
        "Import your location history": "Importiere deinen Standortverlauf",
        "Open an app_export.json or .zip from the LocationHistory2GPX tool — or a Google Timeline location-history.json or .zip from Google Takeout.": "Öffne eine app_export.json oder .zip aus dem LocationHistory2GPX-Tool oder eine Google-Timeline-location-history.json bzw. .zip aus Google Takeout.",
        "Open an LH2GPX app_export.json or .zip from the LocationHistory2GPX tool — or a Google Timeline location-history.json or .zip from Google Takeout.": "Öffne eine LH2GPX-app_export.json oder .zip aus dem LocationHistory2GPX-Tool oder eine Google-Timeline-location-history.json bzw. .zip aus Google Takeout.",
        "Open location history file": "Standortverlauf-Datei öffnen",
        "Load Demo Data": "Demodaten laden",
        "Open Another File": "Andere Datei öffnen",
        "Demo Data": "Demodaten",
        "Reload Demo": "Demo neu laden",
        "Opening location history...": "Standortverlauf wird geöffnet...",
        "Loading demo app export...": "Demo-App-Export wird geladen...",
        "Load Demo": "Demo laden",
        "Import JSON": "JSON importieren",
        "No demo source loaded": "Keine Demoquelle geladen",
        "Load the bundled demo fixture or import a local app_export.json file.": "Lade die gebündelte Demo-Datei oder importiere eine lokale app_export.json-Datei.",
        "Nothing to Export": "Nichts zu exportieren",
        "Import a location history file or save a live track first to enable export.": "Importiere zuerst eine Standortverlauf-Datei oder speichere einen Live-Track, um den Export zu aktivieren.",
        "Select All": "Alle auswählen",
        "Deselect All": "Auswahl aufheben",
        "Preview": "Vorschau",
        "Filter Imported History": "Importierte Historie filtern",
        "Mode": "Modus",
        "Format": "Format",
        "No recorded entries": "Keine erfassten Einträge",
        "No recorded entries for this day": "Keine erfassten Einträge für diesen Tag",
        "No days match \"%@\".": "Keine Tage passen zu \"%@\".",
        "Export markers stay visible directly in the list.": "Export-Markierungen bleiben direkt in der Liste sichtbar.",
        "No Days": "Keine Tage",
        "This export does not contain any day entries.": "Dieser Export enthält keine Tageinträge.",
        "Nothing Recorded": "Nichts aufgezeichnet",
        "This day has no visits, activities or paths in the export.": "Dieser Tag enthält im Export keine Besuche, Aktivitäten oder Routen.",
        "Select a Day": "Tag auswählen",
        "Choose a day from the list to view details.": "Wähle einen Tag aus der Liste, um Details anzuzeigen.",
        "No Day Entries": "Keine Tageinträge",
        "Import a file with day entries to view details.": "Importiere eine Datei mit Tageinträgen, um Details anzuzeigen.",
        "Imported Day Data": "Importierte Tagesdaten",
        "Map, timeline and entry cards below come from the currently imported history file.": "Karte, Zeitachse und Eintragskarten unten stammen aus der aktuell importierten Historie.",
        "Map view requires iOS 17 or later.": "Die Kartenansicht benötigt iOS 17 oder neuer.",
        "Timeline": "Zeitachse",
        "Imported History": "Importierte Historie",
        "Saved tracks are local recordings. They stay separate from imported history until you open one for editing.": "Gespeicherte Tracks sind lokale Aufzeichnungen. Sie bleiben von der importierten Historie getrennt, bis du einen zum Bearbeiten öffnest.",
        "No saved live tracks yet.": "Noch keine gespeicherten Live-Tracks.",
        "Go to any day, open Local Recording, record a short track and switch Record off. The finished track will appear here.": "Gehe zu einem beliebigen Tag, öffne Lokale Aufzeichnung, nimm einen kurzen Track auf und schalte Aufzeichnen wieder aus. Der fertige Track erscheint dann hier.",
        "Summary": "Zusammenfassung",
        "Date": "Datum",
        "Started": "Gestartet",
        "Ended": "Beendet",
        "Points": "Punkte",
        "Map Preview": "Kartenvorschau",
        "Start": "Start",
        "End": "Ende",
        "Point %d": "Punkt %d",
        "Latitude": "Breitengrad",
        "Longitude": "Längengrad",
        "Accuracy (m)": "Genauigkeit (m)",
        "Insert Midpoint": "Mittelpunkt einfügen",
        "Reset": "Zurücksetzen",
        "Save": "Speichern",
        "Delete": "Löschen",
        "Delete saved track?": "Gespeicherten Track löschen?",
        "Delete Track": "Track löschen",
        "This removes the saved track from local storage.": "Dadurch wird der gespeicherte Track aus dem lokalen Speicher entfernt.",
        "Loading...": "Wird geladen...",
        "Source": "Quelle",
        "Schema": "Schema",
        "Exported": "Exportiert",
        "Technical Details": "Technische Details",
        "Distance Over Time": "Strecke im Zeitverlauf",
        "Tap a bar to open the corresponding day.": "Tippe auf einen Balken, um den zugehörigen Tag zu öffnen.",
        "Route distances only": "Nur Routendistanzen",
        "Route distance with recorded-trace fallback.": "Routendistanz mit Fallback auf aufgezeichnete Spur-Geometrie.",
        "Route distance with recorded-trace fallback. Tap a bar to open that day.": "Routendistanz mit Fallback auf aufgezeichnete Spur-Geometrie. Tippe auf einen Balken, um diesen Tag zu öffnen.",
        "No Route Distances": "Keine Routendistanzen",
        "This import does not contain route distance data that could be plotted over time.": "Dieser Import enthält keine Routendistanzdaten, die über die Zeit dargestellt werden könnten.",
        "No route distance or recorded trace data is available for these days.": "Für diese Tage sind weder Routendistanzen noch aufgezeichnete Spur-Daten verfügbar.",
        "Charts Unavailable": "Diagramme nicht verfügbar",
        "This platform build does not include chart rendering for the distance timeline.": "Dieser Plattform-Build enthält keine Diagrammdarstellung für die Distanz-Zeitachse.",
        "Need More Than One Day": "Mehr als ein Tag benötigt",
        "Daily averages become meaningful once the import contains at least two different days.": "Tagesdurchschnitte werden erst sinnvoll, wenn der Import mindestens zwei verschiedene Tage enthält.",
        "Activity Types": "Aktivitätstypen",
        "Compare activities by covered distance.": "Vergleiche Aktivitäten nach zurückgelegter Strecke.",
        "Compare activities by entry count.": "Vergleiche Aktivitäten nach Anzahl der Einträge.",
        "No Activity Breakdown": "Keine Aktivitätsaufschlüsselung",
        "No activity entries were found that could be summarized by type, distance or duration.": "Es wurden keine Aktivitätseinträge gefunden, die nach Typ, Distanz oder Dauer zusammengefasst werden könnten.",
        "Visit Types": "Besuchstypen",
        "No Visit Types": "Keine Besuchstypen",
        "This import does not contain visit data that can be grouped into semantic place types.": "Dieser Import enthält keine Besuchsdaten, die nach semantischen Ortstypen gruppiert werden können.",
        "By Day of Week": "Nach Wochentag",
        "Average visit and activity events per weekday across the imported days.": "Durchschnittliche Besuchs- und Aktivitätsereignisse pro Wochentag über die importierten Tage hinweg.",
        "Average recorded routes per weekday across the imported days.": "Durchschnittlich aufgezeichnete Routen pro Wochentag über die importierten Tage hinweg.",
        "Average visible route distance per weekday, using recorded trace geometry when imported route totals are missing.": "Durchschnittlich sichtbare Routendistanz pro Wochentag, mit Fallback auf aufgezeichnete Spur-Geometrie wenn importierte Routensummen fehlen.",
        "Need More Day Coverage": "Mehr Tagesabdeckung benötigt",
        "A weekday pattern is only shown once at least three separate day summaries are available.": "Ein Wochentagsmuster wird erst angezeigt, wenn mindestens drei getrennte Tageszusammenfassungen verfügbar sind.",
        "This platform build does not include chart rendering for the weekday view.": "Dieser Plattform-Build enthält keine Diagrammdarstellung für die Wochentagsansicht.",
        "Period Breakdown": "Periodenaufschlüsselung",
        "Compare how many imported days contribute to each visible period.": "Vergleiche, wie viele importierte Tage zu jeder sichtbaren Periode beitragen.",
        "Compare the combined visit, activity and route volume across visible periods.": "Vergleiche das kombinierte Besuchs-, Aktivitäts- und Routenvolumen über die sichtbaren Perioden hinweg.",
        "Compare visible route distance by period, using recorded trace geometry when imported route totals are missing.": "Vergleiche die sichtbare Routendistanz nach Periode, mit Fallback auf aufgezeichnete Spur-Geometrie wenn importierte Routensummen fehlen.",
        "No Period Stats": "Keine Periodenstatistiken",
        "This export does not include aggregated month or year period statistics.": "Dieser Export enthält keine aggregierten Monats- oder Jahresstatistiken.",
        "No Insights Yet": "Noch keine Einblicke",
        "This import contains no day entries, so there is nothing meaningful to analyze yet.": "Dieser Import enthält keine Tageinträge, daher gibt es noch nichts Sinnvolles zu analysieren.",
        "Limited Insight Data": "Begrenzte Einblicksdaten",
        "The import loaded correctly, but it does not contain enough structured data for the current insight views yet.": "Der Import wurde korrekt geladen, enthält aber noch nicht genügend strukturierte Daten für die aktuellen Einblick-Ansichten.",
        "Legend": "Legende",
        "Switch to standard map": "Zur Standardkarte wechseln",
        "Switch to satellite map": "Zur Satellitenkarte wechseln",
        "Completed live tracks are saved when you switch recording off. Background recording still depends on Always Allow permission and does not auto-resume after app relaunch.": "Abgeschlossene Live-Tracks werden gespeichert, wenn du Aufzeichnen ausschaltest. Hintergrundaufzeichnung hängt weiterhin von Always-Allow-Freigabe ab und startet nach dem App-Neustart nicht automatisch neu.",
        "Completed live tracks are saved when you switch recording off. No automatic resume runs after app relaunch.": "Abgeschlossene Live-Tracks werden gespeichert, wenn du Aufzeichnen ausschaltest. Nach dem App-Neustart gibt es kein automatisches Fortsetzen.",
        "Record a short local track, switch Record off, then open the Saved Tracks library to edit points, insert midpoints or delete a finished track.": "Nimm einen kurzen lokalen Track auf, schalte Aufzeichnen aus und öffne dann die Saved-Tracks-Mediathek, um Punkte zu bearbeiten, Mittelpunkte einzufügen oder einen fertigen Track zu löschen.",
        "Visit": "Besuch",
        "Distance": "Strecke",
        "Count": "Anzahl",
        "Activity Count": "Aktivitätsanzahl",
        "Visit Count": "Besuchsanzahl",
        "Day": "Tag",
        "Avg": "Durchschn.",
        "Avg events": "Durchschn. Ereignisse",
        "Local export filters are active": "Lokale Exportfilter sind aktiv",
        "Limit imported history by date window or maximum accuracy. Saved Live Tracks stay unaffected by these local export filters.": "Begrenze die importierte Historie nach Datumsfenster oder maximaler Genauigkeit. Gespeicherte Live-Tracks bleiben von diesen lokalen Exportfiltern unberührt.",
        "From": "Von",
        "To": "Bis",
        "Any": "Beliebig",
        "Maximum accuracy": "Maximale Genauigkeit",
        "Required imported content": "Erforderlicher importierter Inhalt",
        "Activity types": "Aktivitätstypen",
        "Area filter": "Gebietsfilter",
        "No Area Filter": "Kein Gebietsfilter",
        "Rectangle": "Rechteck",
        "Custom Shape": "Freie Form",
        "Optional area filters affect imported history only. Saved Live Tracks always keep their full recorded geometry.": "Optionale Gebietsfilter betreffen nur die importierte Historie. Gespeicherte Live-Tracks behalten immer ihre vollständig aufgezeichnete Geometrie.",
        "Enter latitude and longitude bounds. Values are combined with any upstream export filters.": "Gib Breiten- und Längengrad-Grenzen ein. Die Werte werden mit vorhandenen Exportfiltern kombiniert.",
        "Min lat": "Min. Breite",
        "Max lat": "Max. Breite",
        "Min lon": "Min. Länge",
        "Max lon": "Max. Länge",
        "Enter one `lat,lon` pair per line. At least three vertices are required.": "Gib pro Zeile ein `Breite,Länge`-Paar ein. Mindestens drei Eckpunkte sind erforderlich.",
        "The current imported-history filters hide all day rows. Saved Live Tracks can still be exported separately.": "Die aktuellen Importhistorien-Filter blenden alle Tageszeilen aus. Gespeicherte Live-Tracks können weiterhin separat exportiert werden.",
        "Map preview requires a newer Apple platform version, but the export summary below still reflects the current selection.": "Die Kartenvorschau benötigt eine neuere Apple-Plattformversion, aber die Exportzusammenfassung unten spiegelt die aktuelle Auswahl weiterhin wider.",
        "The current selection has no routes with exportable geometry to preview.": "Die aktuelle Auswahl enthält keine Routen mit exportierbaren Verläufen für die Vorschau.",
        "Select content for export": "Inhalt für den Export auswählen",
        "The current selection contains no exportable route paths.": "Die aktuelle Auswahl enthält keine exportierbaren Routenverläufe.",
        "Foreground recording": "Vordergrundaufzeichnung",
        "Background recording": "Hintergrundaufzeichnung",
        "Server upload is enabled, but the URL is invalid.": "Server-Upload ist aktiviert, aber die URL ist ungültig.",
        "Approve while-using-the-app access to show your position and start recording.": "Erlaube Zugriff während der App-Nutzung, um deine Position anzuzeigen und die Aufzeichnung zu starten.",
        "Turn on live location to request foreground-only access.": "Aktiviere Live-Standort, um Zugriff nur im Vordergrund anzufordern.",
        "Location services are restricted on this device. Live recording stays unavailable.": "Die Ortungsdienste sind auf diesem Gerät eingeschränkt. Live-Aufzeichnung bleibt nicht verfügbar.",
        "Enable While Using the App access in Settings to show your position and record live tracks.": "Aktiviere in den Einstellungen Zugriff beim Verwenden der App, um deine Position anzuzeigen und Live-Tracks aufzuzeichnen.",
        "Background recording is enabled in Options, but Apple has only granted While Using the App so far. Approve Always Allow to keep recording when the app leaves the foreground.": "Hintergrundaufzeichnung ist in den Optionen aktiviert, aber Apple hat bisher nur Zugriff beim Verwenden der App gewährt. Erlaube Immer, damit die Aufzeichnung weiterläuft, wenn die App den Vordergrund verlässt.",
        "Recording can continue in the background and stays local to this app until you stop.": "Die Aufzeichnung kann im Hintergrund weiterlaufen und bleibt lokal in dieser App, bis du sie stoppst.",
        "Waiting for accurate foreground location updates.": "Warte auf genaue Standortaktualisierungen im Vordergrund.",
        "Recording stays local to this app and is saved only when you stop.": "Die Aufzeichnung bleibt lokal in dieser App und wird erst gespeichert, wenn du stoppst.",
        "Location is ready. Start recording to capture a live track and keep it running in the background when Always Allow is active.": "Der Standort ist bereit. Starte die Aufzeichnung, um einen Live-Track zu erfassen und ihn im Hintergrund weiterlaufen zu lassen, wenn Immer erlaubt aktiv ist.",
        "Foreground location is authorized. Start recording to show your position and begin a new live track.": "Vordergrund-Standortzugriff ist autorisiert. Starte die Aufzeichnung, um deine Position anzuzeigen und einen neuen Live-Track zu beginnen.",
        "The server returned HTTP %d.": "Der Server hat HTTP %d zurückgegeben."
        ,
        "OK": "OK",
        "Export Failed": "Export fehlgeschlagen",
        "No map content": "Kein Karteninhalt",
        "Selected": "Ausgewählt",
        "Not selected": "Nicht ausgewählt",
        "Latest saved track": "Zuletzt gespeicherter Track",
        "Edit Saved Track": "Gespeicherten Track bearbeiten",
        "This local track library is separate from imported history. Open any saved live track to edit points, insert midpoints or remove it from local storage.": "Diese lokale Track-Mediathek ist von der importierten Historie getrennt. Öffne einen gespeicherten Live-Track, um Punkte zu bearbeiten, Mittelpunkte einzufügen oder ihn aus dem lokalen Speicher zu entfernen.",
        "Live location and saved live tracks stay separate from the imported day data above.": "Live-Standort und gespeicherte Live-Tracks bleiben von den importierten Tagesdaten oben getrennt.",
        "Daily Averages": "Tagesdurchschnitte",
        "Visits / Day": "Besuche / Tag",
        "Activities / Day": "Aktivitäten / Tag",
        "Routes / Day": "Routen / Tag",
        "Distance / Day": "Strecke / Tag",
        "Type": "Typ",
        "Active Source": "Aktive Quelle",
        "Google Timeline": "Google Timeline",
        "No location history loaded": "Kein Standortverlauf geladen",
        "Open an LH2GPX app_export.json or .zip from the LocationHistory2GPX tool, or a Google Timeline location-history.json or .zip. Demo data is available as a fallback.": "Öffne eine LH2GPX-app_export.json oder .zip aus dem LocationHistory2GPX-Tool oder eine Google-Timeline-location-history.json bzw. .zip. Demodaten stehen als Fallback bereit.",
        "Opening location history": "Standortverlauf wird geöffnet",
        "Pending": "Ausstehend",
        "Processing location history data.": "Standortverlaufsdaten werden verarbeitet.",
        "Demo data loaded": "Demodaten geladen",
        "Demo fixture": "Demo-Datei",
        "Bundled demo data is active. Open a local location history file to replace it.": "Gebündelte Demodaten sind aktiv. Öffne eine lokale Standortverlaufsdatei, um sie zu ersetzen.",
        "Bundled demo data decoded successfully but does not contain any day entries.": "Die gebündelten Demodaten wurden erfolgreich dekodiert, enthalten aber keine Tageinträge.",
        "Location history loaded": "Standortverlauf geladen",
        "Imported file": "Importierte Datei",
        "Local file content is active. Open another file to replace it.": "Der Inhalt der lokalen Datei ist aktiv. Öffne eine andere Datei, um ihn zu ersetzen.",
        "The file was decoded successfully but does not contain any day entries.": "Die Datei wurde erfolgreich dekodiert, enthält aber keine Tageinträge.",
        "Unable to open location history": "Standortverlauf konnte nicht geöffnet werden",
        "No location history is currently active. Open a local location history file or load demo data.": "Aktuell ist kein Standortverlauf aktiv. Öffne eine lokale Standortverlaufsdatei oder lade Demodaten.",
        "Last loaded content remains visible": "Zuletzt geladener Inhalt bleibt sichtbar",
        "Current content": "Aktueller Inhalt",
        "The last successfully loaded content remains visible. Open another file to replace it or Clear to reset.": "Der zuletzt erfolgreich geladene Inhalt bleibt sichtbar. Öffne eine andere Datei, um ihn zu ersetzen, oder nutze Leeren zum Zurücksetzen.",
        "Demo data ready": "Demodaten bereit",
        "Location history ready": "Standortverlauf bereit",
        "Open a local location history file or load the bundled demo data.": "Öffne eine lokale Standortverlaufsdatei oder lade die gebündelten Demodaten."
        ,
        "GPS Exchange Format – compatible with most navigation and mapping apps.": "GPS Exchange Format – kompatibel mit den meisten Navigations- und Karten-Apps.",
        "Keyhole Markup Language – useful for Google Earth and other map viewers.": "Keyhole Markup Language – nützlich für Google Earth und andere Kartenbetrachter.",
        "GeoJSON FeatureCollection – useful for browsers, GIS tools, and developer workflows.": "GeoJSON-FeatureCollection – nützlich für Browser, GIS-Werkzeuge und Entwickler-Workflows.",
        "Tracks": "Tracks",
        "Waypoints": "Wegpunkte",
        "Both": "Beides",
        "Double-tap to toggle selection": "Doppeltippen zum Umschalten der Auswahl",
        "No data": "Keine Daten",
        "Replace the current import with another local file.": "Ersetze den aktuellen Import durch eine andere lokale Datei.",
        "Jump into the day list and open imported history entries.": "Wechsle zur Tagesliste und öffne importierte Historieneinträge.",
        "Switch to charts and derived breakdowns for the current import.": "Wechsle zu Diagrammen und Aufschlüsselungen für den aktuellen Import.",
        "Choose days and prepare a GPX export from recorded routes.": "Wähle Tage aus und bereite einen GPX-Export aus aufgezeichneten Routen vor.",
        "Open the separate local track library and edit finished recordings there.": "Öffne die separate lokale Track-Bibliothek und bearbeite dort fertige Aufzeichnungen.",
        "Visualize your movement density on a map.": "Visualisiere deine Bewegungsdichte auf einer Karte.",
        "Open the export sheet for the current imported history.": "Öffne das Export-Fenster für den aktuell importierten Verlauf.",
        "Heatmap": "Heatmap",
        "Fit to data": "Auf Daten zoomen",
        "Controls affect display only.": "Regler beeinflussen nur die Darstellung.",
        "Opacity": "Deckkraft",
        "Radius": "Radius",
        "Low density": "Niedrige Dichte",
        "High density": "Hohe Dichte",
        "Compact": "Kompakt",
        "Wide": "Breit",
        "Saved live tracks live in a separate local library. Record a short track on any day, then open it from here.": "Gespeicherte Live-Tracks liegen in einer separaten lokalen Bibliothek. Nimm einen kurzen Track an einem beliebigen Tag auf und öffne ihn von hier aus.",
        "Open the local track library directly from Overview to edit points, insert midpoints or delete a saved live track.": "Öffne die lokale Track-Bibliothek direkt aus der Übersicht, um Punkte zu bearbeiten, Mittelpunkte einzufügen oder einen gespeicherten Live-Track zu löschen.",
        "Live": "Live",
        "Live Tracking": "Live-Tracking",
        "Live Map": "Live-Karte",
        "Recording": "Aufzeichnung",
        "Idle": "Bereit",
        "Foreground Only": "Nur Vordergrund",
        "Background Ready": "Hintergrund bereit",
        "Upload": "Upload",
        "Advanced": "Erweitert",
        "Track Library": "Track-Mediathek",
        "Patterns": "Muster",
        "Breakdowns": "Aufschlüsselungen",
        "Start Recording": "Aufzeichnung starten",
        "Stop Recording": "Aufzeichnung stoppen",
        "Center": "Zentrieren",
        "Center Map": "Karte zentrieren",
        "Upload Guidance": "Upload-Hinweis",
        "Latest Upload Status": "Letzter Upload-Status",
        "Invalid endpoint": "Ungültiger Endpunkt",
        "Uploading": "Lädt hoch",
        "Paused": "Pausiert",
        "Needs retry": "Wartet auf Wiederholung",
        "Queue pending": "Warteschlange offen",
        "Ready": "Bereit",
        "Endpoint": "Endpunkt",
        "Auth": "Authentifizierung",
        "Batch Size": "Batch-Größe",
        "Queue": "Warteschlange",
        "Failures": "Fehler",
        "Last Success": "Letzter Erfolg",
        "No token": "Kein Token",
        "Token set": "Token gesetzt",
        "Pause Uploads": "Uploads pausieren",
        "Resume Uploads": "Uploads fortsetzen",
        "Flush Queue": "Warteschlange senden",
        "Queued Point": "Wartender Punkt",
        "Queued Points": "Wartende Punkte",
        "Location not available": "Standort nicht verfügbar",
        "Current Speed": "Aktuelle Geschwindigkeit",
        "Average Speed": "Durchschnittsgeschwindigkeit",
        "Last Segment": "Letztes Segment",
        "Update Age": "Alter des Updates",
        "Last Fix": "Letzter Fix",
        "Monthly Trends": "Monatstrends",
        "Top Days": "Top-Tage",
        "No Monthly Trend Yet": "Noch kein Monatstrend",
        "At least one month with visible days is required before this trend becomes meaningful.": "Mindestens ein Monat mit sichtbaren Tagen ist nötig, bevor dieser Trend sinnvoll wird.",
        "Insights Overview": "Einblicke-Übersicht",
        "Days Loaded": "Geladene Tage",
        "Average Distance / Day": "Durchschnittsstrecke / Tag",
        "Across visible days": "Über sichtbare Tage hinweg",
        "Active Months": "Aktive Monate",
        "Months with visible day entries": "Monate mit sichtbaren Tageinträgen",
        "Imported route distance": "Importierte Routendistanz",
        "Route distance with trace fallback": "Routendistanz mit Spur-Fallback",
        "Most Visits": "Meiste Besuche",
        "Most Routes": "Meiste Routen",
        "No Ranked Days Yet": "Noch keine Rangliste möglich",
        "Visible day summaries need at least one visit, route or distance signal before they can be ranked.": "Sichtbare Tageszusammenfassungen brauchen mindestens ein Besuchs-, Routen- oder Distanzsignal, bevor sie gerankt werden können.",
        "Switch between a concise overview, recurring patterns and deeper breakdowns without leaving the current import.": "Wechsle zwischen kompakter Übersicht, wiederkehrenden Mustern und tieferen Aufschlüsselungen, ohne den aktuellen Import zu verlassen.",
        "Spot month-to-month changes in visible route distance, visits, routes or total activity volume.": "Erkenne Monatsveränderungen bei sichtbarer Routendistanz, Besuchen, Routen oder gesamtem Aktivitätsvolumen.",
        "Active Filters": "Aktive Filter",
        "Month": "Monat",
        "Events": "Ereignisse",
        "Visits": "Besuche",
        "Routes": "Routen",
        "Period": "Periode",
        "Avg routes": "Durchschn. Routen",
        "A live session is running. The map follows the latest accepted points and current foreground fix.": "Eine Live-Sitzung läuft. Die Karte folgt den zuletzt akzeptierten Punkten und dem aktuellen Vordergrund-Fix.",
        "Live location is ready. Start a recording or inspect the current fix before you move.": "Live-Standort ist bereit. Starte eine Aufzeichnung oder prüfe den aktuellen Fix, bevor du dich bewegst.",
        "Recording must start once before the app can request foreground location access.": "Die Aufzeichnung muss einmal gestartet werden, bevor die App Standortzugriff im Vordergrund anfordern kann.",
        "Current fix quality, movement speed and queue health update continuously while recording stays active.": "Fixqualität, Bewegungsgeschwindigkeit und Warteschlangenstatus aktualisieren sich laufend, solange die Aufzeichnung aktiv ist.",
        "Start locally, then optionally forward accepted points to your own HTTPS endpoint.": "Starte lokal und leite akzeptierte Punkte optional an deinen eigenen HTTPS-Endpunkt weiter.",
        "Finish the current local track and keep queued uploads ready.": "Beende den aktuellen lokalen Track und halte wartende Uploads bereit.",
        "Begin a new local recording session with the current live settings.": "Beginne eine neue lokale Aufzeichnungssitzung mit den aktuellen Live-Einstellungen.",
        "Review endpoint health, queue pressure and retry state for optional server forwarding.": "Prüfe Endpunktzustand, Warteschlangendruck und Wiederholungsstatus für das optionale Weiterleiten an den Server.",
        "Uploads are paused until you resume them.": "Uploads bleiben pausiert, bis du sie fortsetzt.",
        "Uploads are paused. Resume or flush manually to send queued points.": "Uploads sind pausiert. Setze sie fort oder sende die Warteschlange manuell.",
        "Retry runs on the next accepted point, or you can flush the queue manually.": "Die Wiederholung läuft mit dem nächsten akzeptierten Punkt oder per manuellem Senden der Warteschlange.",
        "Server upload is ready.": "Server-Upload ist bereit.",
        "Server upload is ready. No bearer token is configured.": "Server-Upload ist bereit. Es ist kein Bearer-Token konfiguriert.",
        "Queued points wait until the configured batch size is reached.": "Wartende Punkte bleiben liegen, bis die konfigurierte Batch-Größe erreicht ist.",
        "No queued points to upload.": "Es gibt keine wartenden Punkte zum Hochladen.",
        "Server upload paused.": "Server-Upload pausiert.",
        "Record a short route and stop it once to seed the local track library.": "Nimm eine kurze Strecke auf und stoppe sie einmal, um die lokale Track-Mediathek zu füllen.",
        "Local recordings stay separate from imported history until you open them for editing or export.": "Lokale Aufzeichnungen bleiben von der importierten Historie getrennt, bis du sie zum Bearbeiten oder Exportieren öffnest.",
        "Permission state, background preference and local capture rules remain visible here.": "Berechtigungsstatus, Hintergrundpräferenz und lokale Aufnahme-Regeln bleiben hier sichtbar.",
        "No saved tracks yet": "Noch keine gespeicherten Tracks",
        "Open Track Library": "Track-Mediathek öffnen"
    ]
}
